(function(){const slides=document.querySelectorAll('.hero-slide'),dots=document.querySelectorAll('.slide-dot'),bar=document.getElementById('progress-bar'),DUR=5000;let cur=0,start,raf;function goTo(n){slides[cur].classList.remove('active');dots[cur].classList.remove('active');cur=(n+slides.length)%slides.length;slides[cur].classList.add('active');dots[cur].classList.add('active');reset();}function reset(){bar.style.width='0%';cancelAnimationFrame(raf);start=performance.now();tick();}function tick(){raf=requestAnimationFrame(t=>{const p=Math.min(((t-start)/DUR)*100,100);bar.style.width=p+'%';if(p<100)tick();else setTimeout(()=>goTo(cur+1),80);});}dots.forEach((d,i)=>d.addEventListener('click',()=>goTo(i)));reset();})();

(function(){const btn=document.getElementById('hamburger-btn'),menu=document.getElementById('nav-menu'),bd=document.getElementById('nav-backdrop');let open=false;function toggle(){open=!open;btn.classList.toggle('open',open);menu.classList.toggle('open',open);bd.classList.toggle('open',open);btn.setAttribute('aria-expanded',open);document.body.style.overflow=open?'hidden':'';}btn.addEventListener('click',toggle);bd.addEventListener('click',toggle);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open)toggle();});window.closeMenu=()=>{if(open)toggle();};})();

window.smoothTo=id=>{const el=document.getElementById(id);if(el)el.scrollIntoView({behavior:'smooth'});};
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'});}}));

(function(){const vs=['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=1000&q=85','https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1000&q=85','https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=1000&q=85','https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=1000&q=85'];let c=1,timer;function upd(){const p=(c-1+vs.length)%vs.length,n=(c+1)%vs.length;const lImg=document.querySelector('#vd-left img'),fImg=document.querySelector('#vd-featured img'),rImg=document.querySelector('#vd-right img');if(!lImg)return;lImg.style.opacity='0';fImg.style.opacity='0';rImg.style.opacity='0';setTimeout(()=>{lImg.src=vs[p];fImg.src=vs[c];rImg.src=vs[n];lImg.style.opacity='1';fImg.style.opacity='1';rImg.style.opacity='1';},200);}function next(){c=(c+1)%vs.length;upd();}function prev(){c=(c-1+vs.length)%vs.length;upd();}function startAuto(){timer=setInterval(next,3500);}function resetAuto(){clearInterval(timer);startAuto();}document.getElementById('vd-prev').onclick=()=>{prev();resetAuto();};document.getElementById('vd-next').onclick=()=>{next();resetAuto();};startAuto();})();

// pf-filter active style
const pfs=document.createElement('style');
pfs.textContent='.pf-filter-btn.active,.pf-filter-btn:hover{color:#0e0d0b;background:#bf7c1a;border-color:#bf7c1a;}';
document.head.appendChild(pfs);
gsap.registerPlugin(ScrollTrigger);
gsap.to('.hero-slides',{yPercent:22,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1.2}});
ScrollTrigger.create({trigger:'#about',start:'top 82%',once:true,onEnter:()=>{gsap.to('.g-left',{opacity:1,x:0,duration:1.15,ease:'power3.out'});gsap.to('.g-right',{opacity:1,x:0,duration:1.15,ease:'power3.out',delay:.15});}});
ScrollTrigger.create({trigger:'#services',start:'top 78%',once:true,onEnter:()=>{gsap.to('#services .g-fade',{opacity:1,duration:.7,ease:'power2.out'});gsap.fromTo('.services-big-title',{clipPath:'inset(0 100% 0 0)',opacity:1},{clipPath:'inset(0 0% 0 0)',duration:1.1,ease:'expo.out',delay:.1});gsap.to('#services .g-up',{opacity:1,y:0,duration:.9,ease:'power3.out',stagger:.14,delay:.3});gsap.to('#services .g-right',{opacity:1,x:0,duration:.7,ease:'power3.out',stagger:.1,delay:.2});}});
ScrollTrigger.create({trigger:'#videos-section',start:'top 82%',once:true,onEnter:()=>{gsap.from('.videos-heading-block',{opacity:0,y:28,duration:.85,ease:'power3.out'});gsap.from('.videos-arrows',{opacity:0,x:24,duration:.7,delay:.2,ease:'power2.out'});gsap.from('#vd-left',{opacity:0,x:-55,duration:.95,delay:.18,ease:'power3.out'});gsap.from('#vd-featured',{opacity:0,scale:.9,duration:1.05,delay:.05,ease:'back.out(1.3)'});gsap.from('#vd-right',{opacity:0,x:55,duration:.95,delay:.18,ease:'power3.out'});}});
ScrollTrigger.create({trigger:'#location',start:'top 82%',once:true,onEnter:()=>{gsap.to('.location-overline',{opacity:1,duration:.7,ease:'power2.out'});}});
ScrollTrigger.create({trigger:'#contact',start:'top 82%',once:true,onEnter:()=>{gsap.from('#contact .flex-col',{opacity:0,y:30,duration:.9,ease:'power3.out'});}});